# Generated by Django 3.0.3 on 2020-06-04 11:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 11, 45, 6, 432063, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
