# Generated by Django 3.0.3 on 2020-06-05 02:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200604_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 2, 54, 33, 880999, tzinfo=utc)),
        ),
    ]
