# Generated by Django 3.0.3 on 2020-06-05 07:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200604_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 7, 7, 14, 227623, tzinfo=utc)),
        ),
    ]
