# Generated by Django 3.0.3 on 2020-06-05 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200605_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 9, 23, 34, 605989, tzinfo=utc)),
        ),
    ]
