# Generated by Django 3.0.3 on 2020-06-19 06:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200617_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='faith',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='life',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='movie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 6, 4, 43, 592742, tzinfo=utc)),
        ),
    ]
