# Generated by Django 3.0.3 on 2020-06-30 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200618_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 7, 50, 0, 577144, tzinfo=utc)),
        ),
    ]
